# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expirations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='facility',
            field=models.CharField(choices=[('RWC', 'Redwood City Inpatient'), ('SC', 'Santa Clara Inpatient'), ('SLN', 'San Leandro Inpatient')], default='RWC', max_length=100),
        ),
    ]
