# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expirations', '0003_auto_20170629_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiration',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
